export type User = {
  id: number;
  pseudo: string;
  statuses: UserStatus[];
};

export enum UserStatus {
  EN_ATTENTE_DE_VALIDATION = 1,
  ADHERENT = 3,
  MODERATEUR_TEMPS_CALME = 10,
  MODERATEUR_PHOTOLIVE = 11,
  MODERATEUR_VIDEOLIVE = 12,
  MODERATEUR_METEOALERTE = 13,
  MODERATEUR_FORUMS = 14,
  GESTIONNAIRE_MAILS = 15,
  GESTIONNAIRE_RESEAUX = 16,
  GESTIONNAIRE_STATIC = 17,
  GESTIONNAIRE_CLIMATO = 18,
  GESTIONNAIRE_DONNEES = 19,
  PREVISIONNISTE_REGIONAL = 20,
  PREVISIONNISTE_NATIONAL = 21,
  GESTIONNAIRE_ACTUALITES = 23,
  RESPONSABLE_TECHNIQUE = 40,
  ADMINISTRATEUR = 50,
  MEMBRE_BUREAU = 60,
  BANNI = 99,
}
