export enum BulletinTypes {
  Froid = 'Froid',
  Gel = 'Gel',
  Neige = 'Neige',
  Verglas = 'Verglas',
  Pluie = 'Pluie',
  Inondation = 'Inondation',
  Tempete = 'Tempête',
  Vent = 'Vent',
  Chaleur = 'Chaleur',
  Douceur = 'Douceur',
  Orages = 'Orages',
  Secheresse = 'Sécheresse',
}

export const MAPPING_NUM_TO_TYPE: Record<number, BulletinTypes> = {
  14: BulletinTypes.Froid,
  1: BulletinTypes.Froid,
  12: BulletinTypes.Gel,
  13: BulletinTypes.Gel,
  2: BulletinTypes.Neige,
  16: BulletinTypes.Neige,
  17: BulletinTypes.Neige,
  11: BulletinTypes.Verglas,
  4: BulletinTypes.Pluie,
  5: BulletinTypes.Inondation,
  6: BulletinTypes.Tempete,
  19: BulletinTypes.Vent,
  20: BulletinTypes.Vent,
  7: BulletinTypes.Vent,
  8: BulletinTypes.Chaleur,
  3: BulletinTypes.Douceur,
  9: BulletinTypes.Orages,
  10: BulletinTypes.Secheresse,
};
